# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: assistaCrise
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NWZiNzZhZWY1OTFiYTRmNDRmZDM0OTdlYTcxNWQwYjBjYTI4YWM2MzE5MDczOTcxZGMzMjE5MDRlMTFiODY3ZmM2NzI3MGQxMzBjZWZjMjFiZWY4NTI3NjM1ZDNkNjY3NjFjYjVkYmIxNDVhNjUyMGFmNGEyYTc5YzQzNDcxZjU=
