package fr.uga.assista.domain;

import static fr.uga.assista.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CriseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAllPropertiesEquals(Crise expected, Crise actual) {
        assertCriseAutoGeneratedPropertiesEquals(expected, actual);
        assertCriseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAllUpdatablePropertiesEquals(Crise expected, Crise actual) {
        assertCriseUpdatableFieldsEquals(expected, actual);
        assertCriseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAutoGeneratedPropertiesEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseUpdatableFieldsEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getTypeEvent()).as("check typeEvent").isEqualTo(expected.getTypeEvent()))
            .satisfies(a ->
                assertThat(a.getDateDebut())
                    .as("check dateDebut")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDateDebut())
            )
            .satisfies(a ->
                assertThat(a.getDateFin()).as("check dateFin").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getDateFin())
            )
            .satisfies(a -> assertThat(a.getEstActive()).as("check estActive").isEqualTo(expected.getEstActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseUpdatableRelationshipsEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise relationships")
            .satisfies(a -> assertThat(a.getValidateur()).as("check validateur").isEqualTo(expected.getValidateur()))
            .satisfies(a -> assertThat(a.getSinistreses()).as("check sinistreses").isEqualTo(expected.getSinistreses()));
    }
}
