package fr.uga.assista.domain;

import static fr.uga.assista.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class InformationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationAllPropertiesEquals(Information expected, Information actual) {
        assertInformationAutoGeneratedPropertiesEquals(expected, actual);
        assertInformationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationAllUpdatablePropertiesEquals(Information expected, Information actual) {
        assertInformationUpdatableFieldsEquals(expected, actual);
        assertInformationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationAutoGeneratedPropertiesEquals(Information expected, Information actual) {
        assertThat(actual)
            .as("Verify Information auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationUpdatableFieldsEquals(Information expected, Information actual) {
        assertThat(actual)
            .as("Verify Information relevant properties")
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()))
            .satisfies(a ->
                assertThat(a.getDatePublication())
                    .as("check datePublication")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDatePublication())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationUpdatableRelationshipsEquals(Information expected, Information actual) {
        assertThat(actual)
            .as("Verify Information relationships")
            .satisfies(a -> assertThat(a.getAuteur()).as("check auteur").isEqualTo(expected.getAuteur()))
            .satisfies(a -> assertThat(a.getCrise()).as("check crise").isEqualTo(expected.getCrise()));
    }
}
