package fr.uga.assista.domain;

import static fr.uga.assista.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class OffreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAllPropertiesEquals(Offre expected, Offre actual) {
        assertOffreAutoGeneratedPropertiesEquals(expected, actual);
        assertOffreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAllUpdatablePropertiesEquals(Offre expected, Offre actual) {
        assertOffreUpdatableFieldsEquals(expected, actual);
        assertOffreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAutoGeneratedPropertiesEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreUpdatableFieldsEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getServicePropose()).as("check servicePropose").isEqualTo(expected.getServicePropose()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a ->
                assertThat(a.getDateCreation())
                    .as("check dateCreation")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDateCreation())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreUpdatableRelationshipsEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre relationships")
            .satisfies(a -> assertThat(a.getAuteur()).as("check auteur").isEqualTo(expected.getAuteur()))
            .satisfies(a -> assertThat(a.getCrise()).as("check crise").isEqualTo(expected.getCrise()));
    }
}
